### ISSUE TITLE
FR: image-based background

### ISSUE THREAD

**Issue by yacoob** [marcan/blitzloop#17]
For all of those songs that don't have a sensible video to put in yet, blitzloop could just show a static image. Marginally better than a black screen.

**Comment by marcan** [comment]
Have you tried? Because I bet it already works ever since mpv, just pass an image as the video file :-)

**Comment by marcan** [comment]
More interesting would be to add support for slideshows. mpv can already play a directory of images (just pass it the directory path), but you need to specify the duration with `image-display-duration` and it doesn't work when playing an audio track at the same time. I imagine we'd want fading and Ken Burns compliance eventually, and that would merit implementing our own slideshow image viewer outside of mpv.

But if you just want one still I think that already works :)
