### ISSUE TITLE
FR: fullscreen toggle key

### ISSUE THREAD

**Issue by yacoob** [marcan/blitzloop#18]
For those really lazy sessions, where you don't have >1 display - so you can unfullscreen, queue few songs, fullscreen, enjoy.

No idea how this behaves under Linux, but under OSX, with `fullscreen` on, blitzloop's window is always on top, covering everything else. You can switch to another application, but blitzloop remains on top, covering it.

**Comment by marcan** [comment]
FWIW, there is no such problem on Linux; you can alt-tab away and it won't stay on top. That said, I
