### ISSUE TITLE
Switching to a language other than en-us on the web frontend is broken on Python 3

### ISSUE THREAD

**Issue by delroth** [marcan/blitzloop#28]
Ranging from annoyances (accents getting mangled in the french version) to completely broken (web server stops serving anything due to UnicodeDecodeErrors in the japanese version, requiring the user to clear cookies).

**Comment by marcan** [comment]
Can't repro (on Linux anyway). Note that i18n is implemented entirely client-side (other than storing the setting), so it doesn't make much sense that the Python version would make a difference. Can you dig a bit deeper?

Py3 did cause some spurious (harmless) exceptions when changing language. This is a bottle.py bug in Py3 with empty responses and was already worked around for some other endpoints. I just fixed that in c5f18df. But that shouldn't actually cause anything to break.
