### ISSUE TITLE
English Song Example in Docs

### ISSUE THREAD

**Issue by egelmex** [marcan/blitzloop#41]
An example of file for an English song would be useful for those of use wanting to use blitzloop for English songs.

**Comment by jose1711** [comment]
One way to generate one would be to take a random song in Ultrastar's TXT format and try to convert it using [ultraloop](https://github.com/T045T/ultraloop).

**Comment by marcan** [comment]
I'm actually making music now, so I'll be putting up some examples in English and Japanese soon in a separate repo.
