### ISSUE TITLE
Vocals not heard in multitrack file

### ISSUE THREAD

**Issue by jose1711** [marcan/blitzloop#49]
Not sure if I am doing something wrong or there is some technical issue.
Audio/video: http://download.digitopltd.com/feeds/HDPLUS_Demo.mp4
Related `.blitz` file:
```
[Meta]
title=HDPLUS
artist=Abraxa

[Song]
audio=HDPLUS_Demo.mp4
video=HDPLUS_Demo.mp4
video_offset=0
channels=1

[Timing]
@0.058=0
@171.206=2088

[Formats]
L=Latin

[Styles]
{latin}
font=TakaoPGothic.ttf
size=11
outline_width=0.3
border_width=0.8
colors=ffffff,12309A,000000
colors_on=12309A,ffffff,000000

[Variants]
{latin}
name=latin
tags=L
style=latin

[Lyrics]

L: {foo}
@: 0 10
```
I can toggle between instrumental/vocal audio track using `#` when opened in `mpv` but Vocals slider in blitzloop interface does nothing.

**Comment by marcan** [comment]
BlitzLoop does not expect multiple *tracks* in a single container, but rather multiple pairs of *channels* in a single track (so it can play them in sync and mix them). So you need a 4-channel audio track, with one pair being the instrumental track, and the other the full instrumental+vocal (which BlitzLoop will crossfade between).

For >2 channel pair files, the first pair is the base, and all subsequent pairs should be standalone tracks (e.g. one pair for vocal 1, one pair for vocal 2). In this case BlitzLoop will not crossfade, but rather add the extra tracks at the requested volume.

(The reason for doing it differently for simple files with only one vocal track is that typically the original files are full and instrumental, not a clean vocal track, and even though you can subtract the vocal out, this can *increase* peak levels and you run into clipping issues; keeping the mixes the same as the source data avoids this)

**Comment by jose1711** [comment]
Thank you. For the record for this particular case I had to mux the data from 2 audio tracks into one:
`ffmpeg -i HDPLUS_Demo.mp4 -map 0 -filter_complex "[0:1][0:2]amerge=inputs=2" output.m4a` (and update `.blitz` file).

Having seen it works nicely does that mean #38 is no more valid?

**Comment by marcan** [comment]
Ah, thanks for the reminder. Yup, that's been fixed for a long time now.

**Comment by jose1711** [comment]
Here's what to do if an audio track contains one stereo track, left channel being instrumental-only, right one also containing vocals.
```
ffmpeg -i 'video_(multiplex).mp4' -filter_complex "[0:a]pan=4c|c0=c0|c1=c0|c2=c1|c3=c1[a]" -map "[a]" 'audio.aac'
```
Reopening to consider adding a few sentences (including `ffmpeg` examples) into `Audio file structure` section in `docs/songfiles.md`.

**Comment by marcan** [comment]
Just a hint: be careful with ffmpeg's default AAC encoder, as it causes quite noticeable quality loss. If you're going to be transcoding back to aac, best use `libfdk_aac` (might need an extra library, may not be supported in your build of ffmpeg depending on how anal your distro is about licensing). I would recommend transcoding to opus anyway, or just flac.
