### ISSUE TITLE
FR: ability to disable furigana

### ISSUE THREAD

**Issue by yacoob** [marcan/blitzloop#9]
It's a feature request; I have no idea how feasible this would be, given that kana serves as the basis of timing. It'd be nice to be able to hide furigana, and turn blitzloop into kanji practice tool.

For extra points: instead of on/off, have gradual filters that will remove furigana for all kanjis from selected JLPT level :3

**Comment by marcan** [comment]
This already exists (on a per-song basis): just set the furigana font size to 0, which is interpreted as a special case. Bad Apple!! already has a display option that uses this.

This could easily be added as an out of band global or song selection option if you want it for all songs :)
